dist: xenial
language: rust
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - beta
  - 1.43.0
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
