[package]
name = "secure-packet-transport"
version = "0.1.0"
authors = ["Petr Pudlak <petr.mvd@gmail.com>"]

[dependencies]
# openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "0.9"
openssl = "0.9"
